[versions]
aboutLibraries = "14.0.0-b02" # https://github.com/mikepenz/AboutLibraries/releases
activity = "1.12.3" # https://developer.android.com/jetpack/androidx/releases/activity
agp = "9.0.0" # https://developer.android.com/build/releases/about-agp
compose = "1.7.8"
composeBOM = "2026.01.01" # https://developer.android.com/develop/ui/compose/bom/bom-mapping
composeM3 = "1.5.0-alpha13" # https://developer.android.com/jetpack/androidx/releases/compose-material3
composeM3Adaptive = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive
composeUI = "1.10.2" # https://developer.android.com/jetpack/androidx/releases/compose-ui
core = "1.17.0" # https://developer.android.com/jetpack/androidx/releases/core
coroutines = "1.10.2"
dagger = "2.59.1" # https://github.com/google/dagger/releases
dataStore = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/datastore
desugar = "2.1.5"
gmsMaps = "20.0.0" # https://developers.google.com/android/guides/releases
hilt = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/hilt
kotlin = "2.3.10" # https://github.com/JetBrains/kotlin/releases
ksp = "2.3.4" # https://github.com/google/ksp/releases
leakCanary = "2.14" # https://github.com/square/leakcanary/releases
lifecycle = "2.10.0"
material = "1.13.0"
navigation = "2.9.7" # https://developer.android.com/jetpack/androidx/releases/navigation
serialization = "1.10.0" # https://github.com/Kotlin/kotlinx.serialization/releases
timber = "5.0.1" # https://github.com/JakeWharton/timber/releases

[libraries]
about-libraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
about-libraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutLibraries" }
android-desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
android-gms-play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "gmsMaps" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBOM" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeM3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "composeM3Adaptive" }
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class-android", version.ref = "composeM3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUI" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUI" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
google-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
google-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }