[versions]
aboutLibraries = "13.1.0" # https://github.com/mikepenz/AboutLibraries/releases
activity = "1.12.2"
agp = "8.13.2"
compose = "1.7.8"
composeAdaptive = "1.2.0"
composeBOM = "2025.12.01"
composeM3 = "1.5.0-alpha11"
core = "1.17.0"
coroutines = "1.10.2"
dagger = "2.57.2" # https://github.com/google/dagger/releases
dataStore = "1.2.0"
desugar = "2.1.5"
gmsMaps = "19.2.0"
hiltNavigationCompose = "1.3.0"
# TODO 2.3 when hilt is ready
kotlin = "2.2.21" # https://github.com/JetBrains/kotlin/releases
# TODO 2.3 when hilt is ready
ksp = "2.2.21-2.0.4" # https://github.com/google/ksp/releases
leakCanary = "2.14" # https://github.com/square/leakcanary/releases
lifecycle = "2.10.0"
material = "1.13.0"
navigation = "2.9.6"
serialization = "1.9.0"
timber = "5.0.1" # https://github.com/JakeWharton/timber/releases

[libraries]
about-libraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
android-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
android-gms-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "gmsMaps" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBOM" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeM3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "composeAdaptive" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class-android", version.ref = "composeM3" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }